import { PrismaClient, LedgerEntryType, BillingServiceCategory } from '@prisma/client';

const prisma = new PrismaClient();

const billingServices = [
  // ─────────────────────────────────────────────────────────────────────────────
  // CONSULTATION
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-CONSULT-01',
    name: 'General Consultation',
    description: 'Standard dental consultation and examination',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.CONSULTATION,
    price: 50000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 1,
  },
  {
    serviceCode: 'SVC-CONSULT-02',
    name: 'Emergency Consultation',
    description: 'Urgent dental consultation for pain or trauma',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.CONSULTATION,
    price: 75000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 2,
  },
  {
    serviceCode: 'SVC-CONSULT-03',
    name: 'Specialist Consultation',
    description: 'Consultation with dental specialist (orthodontist, periodontist, etc.)',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.CONSULTATION,
    price: 100000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 3,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // DIAGNOSTIC (IMAGING)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-XRAY-PAN',
    name: 'Panoramic X-Ray',
    description: 'Full mouth panoramic radiograph (OPG)',
    type: LedgerEntryType.IMAGING,
    category: BillingServiceCategory.DIAGNOSTIC,
    price: 80000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 10,
  },
  {
    serviceCode: 'SVC-XRAY-PA',
    name: 'Periapical X-Ray',
    description: 'Single tooth periapical radiograph',
    type: LedgerEntryType.IMAGING,
    category: BillingServiceCategory.DIAGNOSTIC,
    price: 25000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 11,
  },
  {
    serviceCode: 'SVC-XRAY-BW',
    name: 'Bitewing X-Ray',
    description: 'Bitewing radiograph for interproximal caries detection',
    type: LedgerEntryType.IMAGING,
    category: BillingServiceCategory.DIAGNOSTIC,
    price: 25000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 12,
  },
  {
    serviceCode: 'SVC-XRAY-OCCL',
    name: 'Occlusal X-Ray',
    description: 'Occlusal radiograph for broader area coverage',
    type: LedgerEntryType.IMAGING,
    category: BillingServiceCategory.DIAGNOSTIC,
    price: 30000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 13,
  },
  {
    serviceCode: 'SVC-CT-CONE',
    name: 'CBCT Scan',
    description: 'Cone Beam Computed Tomography (3D imaging)',
    type: LedgerEntryType.IMAGING,
    category: BillingServiceCategory.DIAGNOSTIC,
    price: 250000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 14,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // DIAGNOSTIC (LAB)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-LAB-01',
    name: 'General Lab Analysis',
    description: 'General dental laboratory test and analysis',
    type: LedgerEntryType.LAB,
    category: BillingServiceCategory.DIAGNOSTIC,
    price: 40000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 20,
  },
  {
    serviceCode: 'SVC-LAB-BLOOD',
    name: 'Blood Work',
    description: 'Pre-operative blood tests and screening',
    type: LedgerEntryType.LAB,
    category: BillingServiceCategory.DIAGNOSTIC,
    price: 60000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 21,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PROCEDURE (Non-Surgical)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-CLEAN-01',
    name: 'Scaling & Polishing',
    description: 'Professional teeth cleaning (prophylaxis)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 120000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 30,
  },
  {
    serviceCode: 'SVC-CLEAN-02',
    name: 'Deep Cleaning (SRP)',
    description: 'Scaling and root planing for periodontal disease',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 200000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 31,
  },
  {
    serviceCode: 'SVC-FILL-01',
    name: 'Composite Filling (Small)',
    description: 'Small tooth-coloured resin filling (1 surface)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 150000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 32,
  },
  {
    serviceCode: 'SVC-FILL-02',
    name: 'Composite Filling (Medium)',
    description: 'Medium tooth-coloured resin filling (2 surfaces)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 200000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 33,
  },
  {
    serviceCode: 'SVC-FILL-03',
    name: 'Composite Filling (Large)',
    description: 'Large tooth-coloured resin filling (3+ surfaces)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 280000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 34,
  },
  {
    serviceCode: 'SVC-FILL-AMAL',
    name: 'Amalgam Filling',
    description: 'Silver amalgam filling (when specifically requested)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 120000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 35,
  },
  {
    serviceCode: 'SVC-RCT-01',
    name: 'Root Canal Treatment (Single Canal)',
    description: 'Endodontic treatment for single-rooted tooth',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 450000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 36,
  },
  {
    serviceCode: 'SVC-RCT-02',
    name: 'Root Canal Treatment (Multi Canal)',
    description: 'Endodontic treatment for multi-rooted tooth (molars)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 650000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 37,
  },
  {
    serviceCode: 'SVC-RCT-RETX',
    name: 'Root Canal Retreatment',
    description: 'Re-treatment of previously root-canaled tooth',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 750000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 38,
  },
  {
    serviceCode: 'SVC-CROWN-PFM',
    name: 'PFM Crown',
    description: 'Porcelain-fused-to-metal crown',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 600000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 39,
  },
  {
    serviceCode: 'SVC-CROWN-ZIRC',
    name: 'Zirconia Crown',
    description: 'Full zirconia crown (all-ceramic)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 900000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 40,
  },
  {
    serviceCode: 'SVC-CROWN-EMAX',
    name: 'E-Max Crown',
    description: 'Lithium disilicate all-ceramic crown',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 850000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 41,
  },
  {
    serviceCode: 'SVC-BRIDGE-UNIT',
    name: 'Bridge (Per Unit)',
    description: 'Dental bridge per unit (pontic or retainer)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 550000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 42,
  },
  {
    serviceCode: 'SVC-VENEER',
    name: 'Porcelain Veneer',
    description: 'Cosmetic porcelain veneer per tooth',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 750000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 43,
  },
  {
    serviceCode: 'SVC-INLAY-ONLAY',
    name: 'Inlay/Onlay',
    description: 'Ceramic or gold indirect restoration',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.PROCEDURE,
    price: 500000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 44,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SURGICAL
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-EXTR-SIMP',
    name: 'Simple Extraction',
    description: 'Routine single tooth extraction',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 100000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 50,
  },
  {
    serviceCode: 'SVC-EXTR-SURG',
    name: 'Surgical Extraction',
    description: 'Complex or impacted tooth extraction',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 250000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 51,
  },
  {
    serviceCode: 'SVC-EXTR-WISD',
    name: 'Wisdom Tooth Extraction',
    description: 'Third molar extraction (per tooth)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 350000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 52,
  },
  {
    serviceCode: 'SVC-IMPLANT',
    name: 'Dental Implant',
    description: 'Single dental implant placement (fixture only)',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 2500000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 53,
  },
  {
    serviceCode: 'SVC-IMPLANT-ABUT',
    name: 'Implant Abutment',
    description: 'Implant abutment placement',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 800000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 54,
  },
  {
    serviceCode: 'SVC-IMPLANT-CRWN',
    name: 'Implant Crown',
    description: 'Crown on implant',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 1200000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 55,
  },
  {
    serviceCode: 'SVC-BONE-GRFT',
    name: 'Bone Grafting',
    description: 'Ridge augmentation or socket preservation',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 800000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 56,
  },
  {
    serviceCode: 'SVC-SINUS-LIFT',
    name: 'Sinus Lift',
    description: 'Maxillary sinus elevation procedure',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 1500000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 57,
  },
  {
    serviceCode: 'SVC-FRENO',
    name: 'Frenectomy',
    description: 'Labial or lingual frenectomy',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 200000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 58,
  },
  {
    serviceCode: 'SVC-GING-GRFT',
    name: 'Gingival Graft',
    description: 'Soft tissue grafting for recession',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 600000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 59,
  },
  {
    serviceCode: 'SVC-FLAP',
    name: 'Periodontal Flap Surgery',
    description: 'Open flap debridement for advanced periodontitis',
    type: LedgerEntryType.PROCEDURE,
    category: BillingServiceCategory.SURGICAL,
    price: 450000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 60,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // THERAPY
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-ORTHO-CONS',
    name: 'Orthodontic Consultation',
    description: 'Initial orthodontic assessment and treatment planning',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 50000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 70,
  },
  {
    serviceCode: 'SVC-ORTHO-FULL',
    name: 'Full Orthodontic Treatment',
    description: 'Complete braces or aligner treatment (full case)',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 3500000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 71,
  },
  {
    serviceCode: 'SVC-ORTHO-RET',
    name: 'Retainer',
    description: 'Removable or fixed retainer',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 250000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 72,
  },
  {
    serviceCode: 'SVC-ORTHO-ADJ',
    name: 'Orthodontic Adjustment',
    description: 'Regular braces adjustment visit',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 50000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 73,
  },
  {
    serviceCode: 'SVC-ALIGNER',
    name: 'Clear Aligner (Per Arch)',
    description: 'Clear aligner therapy per arch',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 2500000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 74,
  },
  {
    serviceCode: 'SVC-NIGHT-GUARD',
    name: 'Night Guard / Splint',
    description: 'Occlusal splint for bruxism or TMJ',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 350000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 75,
  },
  {
    serviceCode: 'SVC-TMJ-TX',
    name: 'TMJ Treatment',
    description: 'Temporomandibular joint disorder treatment',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 400000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 76,
  },
  {
    serviceCode: 'SVC-WHITEN-TAKE',
    name: 'Take-Home Whitening Kit',
    description: 'Professional take-home bleaching kit with trays',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 450000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 77,
  },
  {
    serviceCode: 'SVC-WHITEN-OFF',
    name: 'In-Office Whitening',
    description: 'Professional in-office teeth whitening',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.THERAPY,
    price: 800000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: true,
    sortOrder: 78,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PREVENTIVE
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-FLUORIDE',
    name: 'Fluoride Treatment',
    description: 'Professional fluoride application',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.PREVENTIVE,
    price: 50000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 80,
  },
  {
    serviceCode: 'SVC-SEALANT',
    name: 'Pit & Fissure Sealant',
    description: 'Dental sealant per tooth',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.PREVENTIVE,
    price: 60000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 81,
  },
  {
    serviceCode: 'SVC-VARNISH',
    name: 'Fluoride Varnish',
    description: 'Fluoride varnish application',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.PREVENTIVE,
    price: 40000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 82,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // MEDICATION / DISPENSING
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-MED-DISP',
    name: 'Medication Dispensing Fee',
    description: 'Fee for dispensing prescribed medications',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.MEDICATION,
    price: 15000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 90,
  },
  {
    serviceCode: 'SVC-ANESTH-LOC',
    name: 'Local Anesthesia',
    description: 'Local anesthetic administration',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.MEDICATION,
    price: 25000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 91,
  },
  {
    serviceCode: 'SVC-SED-LITE',
    name: 'Light Sedation',
    description: 'Nitrous oxide or oral sedation',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.MEDICATION,
    price: 150000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 92,
  },
  {
    serviceCode: 'SVC-SED-IV',
    name: 'IV Sedation',
    description: 'Intravenous conscious sedation',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.MEDICATION,
    price: 500000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 93,
  },
  {
    serviceCode: 'SVC-ANTIBIOTIC',
    name: 'Antibiotic Course',
    description: 'Standard antibiotic prescription',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.MEDICATION,
    price: 50000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 94,
  },
  {
    serviceCode: 'SVC-ANALGESIC',
    name: 'Pain Management Kit',
    description: 'Post-operative pain medication package',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.MEDICATION,
    price: 35000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 95,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // ADMINISTRATIVE
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-ADMIN-REC',
    name: 'Medical Records Copy',
    description: 'Copy of patient dental records',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.ADMINISTRATIVE,
    price: 30000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 100,
  },
  {
    serviceCode: 'SVC-ADMIN-REF',
    name: 'Referral Letter',
    description: 'Specialist referral documentation',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.ADMINISTRATIVE,
    price: 20000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 101,
  },
  {
    serviceCode: 'SVC-ADMIN-CERT',
    name: 'Medical Certificate',
    description: 'Dental fitness or sick leave certificate',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.ADMINISTRATIVE,
    price: 25000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 102,
  },
  {
    serviceCode: 'SVC-ADMIN-CANC',
    name: 'Late Cancellation Fee',
    description: 'Fee for appointments cancelled <24hrs',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.ADMINISTRATIVE,
    price: 50000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 103,
  },
  {
    serviceCode: 'SVC-ADMIN-NOSHOW',
    name: 'No-Show Fee',
    description: 'Fee for missed appointments without notice',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.ADMINISTRATIVE,
    price: 75000,
    currency: 'UGX',
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 104,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // OTHER
  // ─────────────────────────────────────────────────────────────────────────────
  {
    serviceCode: 'SVC-MISC-01',
    name: 'Miscellaneous Service',
    description: 'Custom or undefined service (price negotiable)',
    type: LedgerEntryType.SERVICE,
    category: BillingServiceCategory.OTHER,
    price: 0,
    currency: 'UGX',
    priceRangeMin: 0,
    priceRangeMax: 999999999,
    defaultTaxAmount: 0,
    isActive: true,
    isFavorite: false,
    sortOrder: 999,
    notes: 'Use for custom pricing scenarios',
  },
];

async function main() {
  console.log('🌱 Seeding billing services...');

  // Clear existing data (optional - remove if you want to keep existing)
  // await prisma.billingService.deleteMany();

  let created = 0;
  let skipped = 0;

  for (const service of billingServices) {
    const existing = await prisma.billingService.findUnique({
      where: { serviceCode: service.serviceCode },
    });

    if (existing) {
      console.log(`  ⏭️  Skipping ${service.serviceCode} (already exists)`);
      skipped++;
    } else {
      await prisma.billingService.create({ data: service });
      console.log(`  ✅ Created ${service.serviceCode}: ${service.name}`);
      created++;
    }
  }

  console.log(`\n✨ Done! Created ${created} services, skipped ${skipped} existing.`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });