// prisma/seed-procedures.ts
import { PrismaClient, PricingModel, BillingUnit } from '@prisma/client';

const prisma = new PrismaClient();

// Category definitions with colors and icons
const categories = [
  { name: 'Consultation', color: '#4A90D9', icon: 'stethoscope', sortOrder: 1 },
  {
    name: 'Conservative and Endodontics',
    color: '#E74C3C',
    icon: 'tooth',
    sortOrder: 2,
  },
  { name: 'Pedodontics', color: '#F39C12', icon: 'baby', sortOrder: 3 },
  { name: 'Surgery', color: '#9B59B6', icon: 'scalpel', sortOrder: 4 },
  { name: 'Prosthodontics', color: '#1ABC9C', icon: 'crown', sortOrder: 5 },
  { name: 'Periodontics', color: '#E67E22', icon: 'gum', sortOrder: 6 },
  { name: 'Orthodontics', color: '#3498DB', icon: 'braces', sortOrder: 7 },
  { name: 'Implantology', color: '#2ECC71', icon: 'implant', sortOrder: 8 },
];

// Helper to map old pricingUnit to new schema
function mapPricingUnit(
  pricingUnit: string,
  price: number,
): {
  pricingModel: PricingModel;
  billingUnit: BillingUnit | null;
  basePrice: string;
  priceRangeMin?: string;
  priceRangeMax?: string;
} {
  switch (pricingUnit) {
    case 'PER_TOOTH':
      return {
        pricingModel: PricingModel.PER_TOOTH,
        billingUnit: BillingUnit.TOOTH,
        basePrice: price.toString(),
      };
    case 'PER_ARCH':
      return {
        pricingModel: PricingModel.PER_ARCH,
        billingUnit: BillingUnit.ARCH,
        basePrice: price.toString(),
      };
    case 'FIXED':
    default:
      return {
        pricingModel: PricingModel.FIXED,
        billingUnit: null,
        basePrice: price.toString(),
      };
  }
}

async function main() {
  console.log('Seeding procedure categories...');

  // Create categories first
  const categoryMap: Record<string, string> = {};

  for (const cat of categories) {
    const category = await prisma.procedureCategory.upsert({
      where: { name: cat.name },
      update: {
        color: cat.color,
        icon: cat.icon,
        sortOrder: cat.sortOrder,
        updatedAt: new Date(),
      },
      create: {
        name: cat.name,
        color: cat.color,
        icon: cat.icon,
        sortOrder: cat.sortOrder,
        isActive: true,
      },
    });
    categoryMap[cat.name] = category.id;
    console.log(`  ✓ Category: ${cat.name}`);
  }

  console.log('\nSeeding procedures...');

  const procedures = [
    // CONSULTATION
    {
      code: 'CONS-GEN',
      name: 'General Consultation',
      category: 'Consultation',
      description: 'General dental consultation and examination',
      baseCost: 0,
      basePrice: 15000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },

    // CONSERVATIVE AND ENDODONTICS
    {
      code: 'FILL-COMP-C5S',
      name: 'Composite Filling Class V & I Shallow',
      category: 'Conservative and Endodontics',
      description:
        'Composite resin restoration for Class V and shallow Class I cavities',
      baseCost: 0,
      basePrice: 50000,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'FILL-COMP-C34D',
      name: 'Composite Filling Class III, IV & I Deep',
      category: 'Conservative and Endodontics',
      description:
        'Composite resin restoration for Class III, IV and deep Class I cavities',
      baseCost: 0,
      basePrice: 80000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'FILL-COMP-C2',
      name: 'Composite Filling Class II',
      category: 'Conservative and Endodontics',
      description: 'Composite resin restoration for Class II cavities',
      baseCost: 0,
      basePrice: 100000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'FILL-IPC',
      name: 'Indirect Pulp Capping',
      category: 'Conservative and Endodontics',
      description: 'Indirect pulp capping procedure',
      baseCost: 0,
      basePrice: 100000,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'FILL-GIC',
      name: 'GIC Filling',
      category: 'Conservative and Endodontics',
      description: 'Glass ionomer cement restoration',
      baseCost: 0,
      basePrice: 50000,
      defaultDuration: 30,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'VENEER-COMP',
      name: 'Composite Veneers',
      category: 'Conservative and Endodontics',
      description: 'Direct composite resin veneers',
      baseCost: 0,
      basePrice: 50000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'RCT-1C',
      name: 'Root Canal Treatment - 1 Canal',
      category: 'Conservative and Endodontics',
      description: 'Endodontic treatment for single canal tooth',
      baseCost: 0,
      basePrice: 200000,
      defaultDuration: 90,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'RCT-2C',
      name: 'Root Canal Treatment - 2 Canals',
      category: 'Conservative and Endodontics',
      description: 'Endodontic treatment for two canal tooth',
      baseCost: 0,
      basePrice: 250000,
      defaultDuration: 105,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'RCT-3-4C',
      name: 'Root Canal Treatment - 3 to 4 Canals',
      category: 'Conservative and Endodontics',
      description: 'Endodontic treatment for multi-canal tooth',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 120,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'RCT-RETX',
      name: 'Root Canal Retreatment',
      category: 'Conservative and Endodontics',
      description: 'Re-treatment of previously root canal treated tooth',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 120,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'POST-CORE',
      name: 'Post and Core Build-up',
      category: 'Conservative and Endodontics',
      description: 'Post placement and core build-up',
      baseCost: 0,
      basePrice: 350000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'BLEACH-OFFICE',
      name: 'In-Office Bleaching',
      category: 'Conservative and Endodontics',
      description: 'Professional teeth whitening',
      baseCost: 0,
      basePrice: 800000,
      defaultDuration: 90,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'XRAY-PA',
      name: 'Periapical X-Ray',
      category: 'Conservative and Endodontics',
      description: 'Single periapical radiograph',
      baseCost: 0,
      basePrice: 25000,
      defaultDuration: 15,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'XRAY-PA-RCT',
      name: 'X-Ray Within RCT',
      category: 'Conservative and Endodontics',
      description: 'Periapical radiograph during RCT',
      baseCost: 0,
      basePrice: 15000,
      defaultDuration: 10,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'FILL-AMAL',
      name: 'Amalgam Restoration',
      category: 'Conservative and Endodontics',
      description: 'Silver amalgam filling',
      baseCost: 50000,
      basePrice: 0,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },

    // PEDODONTICS
    {
      code: 'PEDO-EXT',
      name: 'Pediatric Extraction',
      category: 'Pedodontics',
      description: 'Simple extraction for pediatric patients',
      baseCost: 30000,
      basePrice: 0,
      defaultDuration: 20,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PEDO-FILL-GIC',
      name: 'Pediatric GIC Filling',
      category: 'Pedodontics',
      description: 'GIC filling for primary teeth',
      baseCost: 0,
      basePrice: 35000,
      defaultDuration: 30,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PEDO-PULPOT',
      name: 'Pulpotomy',
      category: 'Pedodontics',
      description: 'Coronal pulp removal in primary teeth',
      baseCost: 0,
      basePrice: 40000,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'PEDO-PULPEC',
      name: 'Pulpectomy',
      category: 'Pedodontics',
      description: 'Complete pulp removal in primary teeth',
      baseCost: 0,
      basePrice: 100000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'PEDO-SSC',
      name: 'Stainless Steel Crown',
      category: 'Pedodontics',
      description: 'SSC for primary teeth',
      baseCost: 0,
      basePrice: 200000,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PEDO-SM-BL',
      name: 'Space Maintainer - Band and Loop',
      category: 'Pedodontics',
      description: 'Fixed space maintainer',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 60,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'PEDO-SCALE',
      name: 'Pediatric Scaling',
      category: 'Pedodontics',
      description: 'Cleaning for pediatric patients',
      baseCost: 0,
      basePrice: 40000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PEDO-FLUOR',
      name: 'Fluoride Application',
      category: 'Pedodontics',
      description: 'Professional fluoride treatment',
      baseCost: 0,
      basePrice: 50000,
      defaultDuration: 20,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PEDO-SEAL',
      name: 'Pit and Fissure Sealant',
      category: 'Pedodontics',
      description: 'Preventive sealant',
      baseCost: 0,
      basePrice: 50000,
      defaultDuration: 30,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PEDO-SURG-EXP',
      name: 'Surgical Exposure of Unerupted Teeth',
      category: 'Pedodontics',
      description: 'Exposure of impacted teeth',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },

    // SURGERY
    {
      code: 'EXT-ANT',
      name: 'Extraction - Anterior',
      category: 'Surgery',
      description: 'Extraction of incisors or canines',
      baseCost: 0,
      basePrice: 50000,
      defaultDuration: 20,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'EXT-PREM',
      name: 'Extraction - Premolar',
      category: 'Surgery',
      description: 'Extraction of premolars',
      baseCost: 0,
      basePrice: 60000,
      defaultDuration: 25,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'EXT-MOL',
      name: 'Extraction - Molars',
      category: 'Surgery',
      description: 'Extraction of molars',
      baseCost: 0,
      basePrice: 70000,
      defaultDuration: 30,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'EXT-WIS',
      name: 'Extraction - Wisdom Teeth',
      category: 'Surgery',
      description: 'Extraction of third molars',
      baseCost: 0,
      basePrice: 80000,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'EXT-SURG-SIMP',
      name: 'Surgical Extraction - Simple',
      category: 'Surgery',
      description: 'Surgical removal requiring flap',
      baseCost: 0,
      basePrice: 100000,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'EXT-SURG-COMP',
      name: 'Surgical Extraction - Complicated',
      category: 'Surgery',
      description: 'Complex surgical extraction',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 90,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'SURG-FREN',
      name: 'Frenectomy',
      category: 'Surgery',
      description: 'Frenum removal or modification',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'SURG-EXC',
      name: 'Surgical Excision',
      category: 'Surgery',
      description: 'Excision of soft tissue lesions',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 45,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'SURG-DRAIN',
      name: 'Surgical Drainage',
      category: 'Surgery',
      description: 'Incision and drainage of abscess',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'SURG-EYELET',
      name: 'Eyelet Wiring',
      category: 'Surgery',
      description: 'Maxillofacial trauma stabilization',
      baseCost: 0,
      basePrice: 100000,
      defaultDuration: 60,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'SURG-IMF',
      name: 'IMF (Intermaxillary Fixation)',
      category: 'Surgery',
      description: 'Jaw wiring for trauma',
      baseCost: 0,
      basePrice: 1000000,
      defaultDuration: 90,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },

    // PROSTHODONTICS - Removable
    {
      code: 'PROS-CD-BOTH',
      name: 'Complete Denture - Upper and Lower',
      category: 'Prosthodontics',
      description: 'Full mouth dentures',
      baseCost: 0,
      basePrice: 3000000,
      defaultDuration: 120,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PROS-CD-ARCH',
      name: 'Complete Denture - One Arch',
      category: 'Prosthodontics',
      description: 'Single arch complete denture',
      baseCost: 0,
      basePrice: 1500000,
      defaultDuration: 90,
      pricingUnit: 'PER_ARCH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PROS-RPD',
      name: 'Partial Denture (Acrylic)',
      category: 'Prosthodontics',
      description: 'Removable partial denture',
      baseCost: 0,
      basePrice: 100000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
      priceRangeMin: 200000,
    },
    {
      code: 'PROS-RPD-FLEX',
      name: 'Flexible Partial Denture',
      category: 'Prosthodontics',
      description: 'Valplast flexible denture',
      baseCost: 0,
      basePrice: 160000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
      priceRangeMin: 300000,
    },
    {
      code: 'PROS-REP',
      name: 'Denture Repair/Addition',
      category: 'Prosthodontics',
      description: 'Repair or addition of tooth/clasp',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 45,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PROS-REBASE',
      name: 'Denture Rebasing and Relining',
      category: 'Prosthodontics',
      description: 'Base or lining replacement',
      baseCost: 0,
      basePrice: 120000,
      defaultDuration: 60,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PROS-NG',
      name: 'Night Guard',
      category: 'Prosthodontics',
      description: 'Occlusal guard for bruxism',
      baseCost: 0,
      basePrice: 210000,
      defaultDuration: 45,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },

    // PROSTHODONTICS - Fixed
    {
      code: 'PROS-FIX-ACR',
      name: 'Fixed Prosthesis - Acrylic',
      category: 'Prosthodontics',
      description: 'Acrylic crown',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PROS-FIX-PFM',
      name: 'PFM Crown',
      category: 'Prosthodontics',
      description: 'Porcelain-fused-to-metal crown',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'PROS-FIX-ZIRC',
      name: 'Full Zirconia Crown',
      category: 'Prosthodontics',
      description: 'All-ceramic zirconia crown',
      baseCost: 0,
      basePrice: 600000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'PROS-VENEER-ZIRC',
      name: 'Zirconia Veneer',
      category: 'Prosthodontics',
      description: 'Zirconia porcelain veneer',
      baseCost: 0,
      basePrice: 600000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PROS-INLAY',
      name: 'Inlay/Onlay',
      category: 'Prosthodontics',
      description: 'Indirect ceramic/composite restoration',
      baseCost: 0,
      basePrice: 600000,
      defaultDuration: 60,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },

    // PERIODONTICS
    {
      code: 'PERIO-SCALE-MILD',
      name: 'Full Mouth Scaling - Mild',
      category: 'Periodontics',
      description: 'Cleaning for mild gingivitis',
      baseCost: 0,
      basePrice: 80000,
      defaultDuration: 45,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PERIO-SCALE-MOD',
      name: 'Full Mouth Scaling - Moderate',
      category: 'Periodontics',
      description: 'Scaling for moderate calculus',
      baseCost: 0,
      basePrice: 100000,
      defaultDuration: 60,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PERIO-SCALE-SEV',
      name: 'Full Mouth Scaling - Severe',
      category: 'Periodontics',
      description: 'Deep cleaning for periodontal disease',
      baseCost: 0,
      basePrice: 120000,
      defaultDuration: 90,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'PERIO-GING-S',
      name: 'Gingivectomy - Single Tooth',
      category: 'Periodontics',
      description: 'Gum tissue removal around single tooth',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 30,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'PERIO-GING-ARCH',
      name: 'Gingivectomy - Full Arch',
      category: 'Periodontics',
      description: 'Full arch gingivectomy',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 90,
      pricingUnit: 'PER_ARCH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },

    // ORTHODONTICS
    {
      code: 'ORTHO-FIX-1',
      name: 'Fixed Orthodontics - One Arch',
      category: 'Orthodontics',
      description: 'Fixed appliance treatment (single arch)',
      baseCost: 0,
      basePrice: 900000,
      defaultDuration: 30,
      pricingUnit: 'PER_ARCH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'ORTHO-FIX-BOTH',
      name: 'Fixed Orthodontics - Both Arches',
      category: 'Orthodontics',
      description: 'Fixed appliance treatment (full mouth)',
      baseCost: 0,
      basePrice: 1800000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'ORTHO-REM-JACK',
      name: 'Removable Appliance - Jack Screw',
      category: 'Orthodontics',
      description: 'Active removable appliance',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'ORTHO-HYRAX',
      name: 'Fixed Appliance - Hyrax',
      category: 'Orthodontics',
      description: 'Rapid palatal expander',
      baseCost: 0,
      basePrice: 500000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'ORTHO-RET-HAW',
      name: 'Removable Retainer - Hawley',
      category: 'Orthodontics',
      description: 'Traditional Hawley retainer',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 30,
      pricingUnit: 'PER_ARCH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'ORTHO-RET-ESS',
      name: 'Removable Retainer - Essix',
      category: 'Orthodontics',
      description: 'Clear vacuum-formed retainer',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 20,
      pricingUnit: 'PER_ARCH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'ORTHO-RET-FIX',
      name: 'Fixed Retainer',
      category: 'Orthodontics',
      description: 'Bonded lingual retainer',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 30,
      pricingUnit: 'PER_ARCH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'ORTHO-HABIT',
      name: 'Habit Breaking Appliance',
      category: 'Orthodontics',
      description: 'Appliance for thumb sucking/tongue thrust',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'ORTHO-FOLLOW',
      name: 'Orthodontic Follow-up',
      category: 'Orthodontics',
      description: 'Adjustment and monitoring visit',
      baseCost: 0,
      basePrice: 40000,
      defaultDuration: 20,
      pricingUnit: 'PER_ARCH',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'ORTHO-REBOND',
      name: 'Re-bonding of Bracket/Buccal Tube',
      category: 'Orthodontics',
      description: 'Re-cementation of loose attachment',
      baseCost: 0,
      basePrice: 20000,
      defaultDuration: 15,
      pricingUnit: 'PER_UNIT',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'ORTHO-LOST-BRACK',
      name: 'Replacement of Lost Bracket/Buccal Tube',
      category: 'Orthodontics',
      description: 'New bracket or tube replacement',
      baseCost: 0,
      basePrice: 35000,
      defaultDuration: 20,
      pricingUnit: 'PER_UNIT',
      currency: 'UGX',
      requiresXray: false,
      isActive: true,
    },
    {
      code: 'ORTHO-FUNC',
      name: 'Functional Appliance',
      category: 'Orthodontics',
      description: 'Twin block or functional appliance',
      baseCost: 0,
      basePrice: 300000,
      defaultDuration: 30,
      pricingUnit: 'FIXED',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'ORTHO-CAN-EXP',
      name: 'Canine Exposure',
      category: 'Orthodontics',
      description: 'Surgical exposure for orthodontic traction',
      baseCost: 0,
      basePrice: 150000,
      defaultDuration: 45,
      pricingUnit: 'PER_TOOTH',
      currency: 'UGX',
      requiresXray: true,
      isActive: true,
    },

    // IMPLANTOLOGY
    {
      code: 'IMPL-SINGLE',
      name: 'Single Dental Implant',
      category: 'Implantology',
      description: 'Single tooth implant placement',
      baseCost: 0,
      basePrice: 800,
      defaultDuration: 60,
      pricingUnit: 'FIXED',
      currency: 'USD',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'IMPL-SINGLE-GRAFT',
      name: 'Single Implant with Bone Graft',
      category: 'Implantology',
      description: 'Implant with simultaneous bone grafting',
      baseCost: 0,
      basePrice: 1000,
      defaultDuration: 90,
      pricingUnit: 'FIXED',
      currency: 'USD',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'IMPL-CD-ARCH',
      name: 'Implant-Supported Complete Denture - One Arch',
      category: 'Implantology',
      description: 'Overdenture supported by 2-4 implants',
      baseCost: 0,
      basePrice: 5000,
      defaultDuration: 120,
      pricingUnit: 'PER_ARCH',
      currency: 'USD',
      requiresXray: true,
      isActive: true,
    },
    {
      code: 'IMPL-CD-BOTH',
      name: 'Implant-Supported Complete Denture - Both Arches',
      category: 'Implantology',
      description: 'Full mouth implant-supported overdentures',
      baseCost: 0,
      basePrice: 10000,
      defaultDuration: 180,
      pricingUnit: 'FIXED',
      currency: 'USD',
      requiresXray: true,
      isActive: true,
    },
  ];

  // Insert procedures with upsert
  for (const procedure of procedures) {
    const categoryId = categoryMap[procedure.category];
    if (!categoryId) {
      console.warn(
        `  ⚠ Skipping ${procedure.code}: category "${procedure.category}" not found`,
      );
      continue;
    }

    const pricing = mapPricingUnit(procedure.pricingUnit, procedure.basePrice);

    // Handle special case for PER_UNIT (orthodontics)
    let billingUnit = pricing.billingUnit;
    if (procedure.pricingUnit === 'PER_UNIT') {
      billingUnit = BillingUnit.UNIT;
    }

    await prisma.procedure.upsert({
      where: { code: procedure.code },
      update: {
        name: procedure.name,
        categoryId: categoryId,
        description: procedure.description,
        baseCost: procedure.baseCost.toString(),
        basePrice: procedure.basePrice.toString(),
        pricingModel: pricing.pricingModel,
        billingUnit: billingUnit,
        priceRangeMin: procedure.priceRangeMin?.toString() ?? null,
        priceRangeMax:
          'priceRangeMax' in procedure && procedure.priceRangeMax
            ? procedure.priceRangeMax.toString()
            : null,
        currency: procedure.currency,
        defaultDuration: procedure.defaultDuration,
        requiresXray: procedure.requiresXray,
        isActive: procedure.isActive,
        updatedAt: new Date(),
      },
      create: {
        code: procedure.code,
        name: procedure.name,
        categoryId: categoryId,
        description: procedure.description,
        baseCost: procedure.baseCost.toString(),
        basePrice: procedure.basePrice.toString(),
        pricingModel: pricing.pricingModel,
        billingUnit: billingUnit,
        priceRangeMin: procedure.priceRangeMin?.toString() ?? null,
        priceRangeMax:
          'priceRangeMax' in procedure && procedure.priceRangeMax
            ? procedure.priceRangeMax.toString()
            : null,
        currency: procedure.currency,
        defaultDuration: procedure.defaultDuration,
        requiresXray: procedure.requiresXray,
        isActive: procedure.isActive,
      },
    });

    console.log(`  ✓ ${procedure.code}: ${procedure.name}`);
  }

  console.log(`\n✅ Seeded ${procedures.length} procedures successfully`);
}

main()
  .catch((e) => {
    console.error('Error seeding procedures:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
