// prisma/seed/procedures.seed.ts
import { PrismaClient, PricingModel, BillingUnit } from '@prisma/client';

const prisma = new PrismaClient();

// Define all procedures grouped by category code.
// The category codes match those we seeded earlier:
//   CONS-ENDO, PEDO, SURG, PROS, FIXED-PROS, PERIO, ORTHO, IMPLANT
const procedures = [
  // ── CONSERVATIVE & ENDODONTICS ────────────────────────────────────────
  {
    id: 'proc_001',
    code: 'CONS-COMP-5-1-SHALLOW',
    name: 'Composite class 5 and 1 shallow',
    categoryCode: 'CONS-ENDO',
    basePrice: 50000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Shallow composite restoration, per tooth',
  },
  {
    id: 'proc_002',
    code: 'CONS-COMP-3-4-1-DEEP',
    name: 'Composite class 3,4,1 deep',
    categoryCode: 'CONS-ENDO',
    basePrice: 80000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Deep composite restoration, per tooth',
  },
  {
    id: 'proc_003',
    code: 'CONS-COMP-2',
    name: 'Composite class 2',
    categoryCode: 'CONS-ENDO',
    basePrice: 100000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Class II composite restoration, per tooth',
  },
  {
    id: 'proc_004',
    code: 'CONS-INDIRECT-PULP',
    name: 'Indirect pulp capping',
    categoryCode: 'CONS-ENDO',
    basePrice: 100000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Indirect pulp capping procedure, per tooth',
  },
  {
    id: 'proc_005',
    code: 'CONS-GIC',
    name: 'GIC filling',
    categoryCode: 'CONS-ENDO',
    basePrice: 50000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Glass ionomer cement filling, per tooth',
  },
  {
    id: 'proc_006',
    code: 'CONS-COMP-VENEER',
    name: 'Composite veneers',
    categoryCode: 'CONS-ENDO',
    basePrice: 50000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Direct composite veneer, per tooth',
  },
  {
    id: 'proc_007',
    code: 'CONS-RCT-1CANAL',
    name: 'Root canal 1 canal',
    categoryCode: 'CONS-ENDO',
    basePrice: 200000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Root canal treatment – 1 canal, per tooth',
  },
  {
    id: 'proc_008',
    code: 'CONS-RCT-2CANALS',
    name: 'Root canal 2 canals',
    categoryCode: 'CONS-ENDO',
    basePrice: 250000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Root canal treatment – 2 canals, per tooth',
  },
  {
    id: 'proc_009',
    code: 'CONS-RCT-3-4CANALS',
    name: 'Root canal 3 to 4 canals',
    categoryCode: 'CONS-ENDO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Root canal treatment – 3 or 4 canals, per tooth',
  },
  {
    id: 'proc_010',
    code: 'CONS-RCT-RETREAT',
    name: 'Retreatment RCT',
    categoryCode: 'CONS-ENDO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Endodontic retreatment, per tooth',
  },
  {
    id: 'proc_011',
    code: 'CONS-POST-CORE',
    name: 'Post and core build up',
    categoryCode: 'CONS-ENDO',
    basePrice: 350000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Post and core build‑up after root canal, per tooth',
  },
  {
    id: 'proc_012',
    code: 'CONS-BLEACHING',
    name: 'Bleaching',
    categoryCode: 'CONS-ENDO',
    basePrice: 800000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'In‑office bleaching (full mouth)',
  },
  {
    id: 'proc_013',
    code: 'CONS-XRAY',
    name: 'X-ray',
    categoryCode: 'CONS-ENDO',
    basePrice: 25000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Periapical / bitewing x‑ray, per image',
  },
  {
    id: 'proc_014',
    code: 'CONS-XRAY-RCT',
    name: 'X-ray within RCT',
    categoryCode: 'CONS-ENDO',
    basePrice: 15000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'X‑ray taken during root canal treatment',
  },
  {
    id: 'proc_015',
    code: 'CONS-AMALGAM',
    name: 'Amalgam restoration',
    categoryCode: 'CONS-ENDO',
    basePrice: 50000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Amalgam filling, per tooth',
  },

  // ── PEDODONTICS ──────────────────────────────────────────────────────
  {
    id: 'proc_016',
    code: 'PEDO-EXTR',
    name: 'Extraction',
    categoryCode: 'PEDO',
    basePrice: 30000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Primary tooth extraction, per tooth',
  },
  {
    id: 'proc_017',
    code: 'PEDO-FILL-GIC',
    name: 'Filling GIC',
    categoryCode: 'PEDO',
    basePrice: 35000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'GIC filling on primary teeth, per tooth',
  },
  {
    id: 'proc_018',
    code: 'PEDO-PULPOTOMY',
    name: 'Pulpotomy',
    categoryCode: 'PEDO',
    basePrice: 40000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Pulpotomy on primary tooth, per tooth',
  },
  {
    id: 'proc_019',
    code: 'PEDO-PULPECTOMY',
    name: 'Pulpectomy',
    categoryCode: 'PEDO',
    basePrice: 100000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Pulpectomy on primary tooth, per tooth',
  },
  {
    id: 'proc_020',
    code: 'PEDO-SSC',
    name: 'Stainless steel crown',
    categoryCode: 'PEDO',
    basePrice: 200000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Preformed stainless steel crown, per tooth',
  },
  {
    id: 'proc_021',
    code: 'PEDO-SPACE-MAINTAINER',
    name: 'Space maintainer band and loop',
    categoryCode: 'PEDO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Fixed band‑and‑loop space maintainer, per appliance',
  },
  {
    id: 'proc_022',
    code: 'PEDO-SCALING',
    name: 'Scaling',
    categoryCode: 'PEDO',
    basePrice: 40000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Paediatric scaling (full mouth)',
  },
  {
    id: 'proc_023',
    code: 'PEDO-FLUORIDE',
    name: 'Fluoride application',
    categoryCode: 'PEDO',
    basePrice: 50000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Topical fluoride varnish application',
  },
  {
    id: 'proc_024',
    code: 'PEDO-SEALANT',
    name: 'Pit and fissure sealant',
    categoryCode: 'PEDO',
    basePrice: 50000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Fissure sealant, per tooth',
  },
  {
    id: 'proc_025',
    code: 'PEDO-EXPOSURE',
    name: 'Surgical exposure of unerupted teeth',
    categoryCode: 'PEDO',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Surgical exposure of impacted/unerupted tooth, per tooth',
  },

  // ── SURGERY ──────────────────────────────────────────────────────────
  {
    id: 'proc_026',
    code: 'SURG-EXTR-ANT',
    name: 'Extraction anterior',
    categoryCode: 'SURG',
    basePrice: 50000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Simple extraction – anterior, per tooth',
  },
  {
    id: 'proc_027',
    code: 'SURG-EXTR-PREMOLAR',
    name: 'Extraction premolar',
    categoryCode: 'SURG',
    basePrice: 60000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Simple extraction – premolar, per tooth',
  },
  {
    id: 'proc_028',
    code: 'SURG-EXTR-MOLAR',
    name: 'Extraction molars',
    categoryCode: 'SURG',
    basePrice: 70000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Simple extraction – molar, per tooth',
  },
  {
    id: 'proc_029',
    code: 'SURG-EXTR-WISDOM',
    name: 'Extraction of wisdom teeth',
    categoryCode: 'SURG',
    basePrice: 80000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Simple wisdom tooth extraction, per tooth',
  },
  {
    id: 'proc_030',
    code: 'SURG-SURGICAL-SIMPLE',
    name: 'Surgical extraction simple',
    categoryCode: 'SURG',
    basePrice: 100000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Simple surgical extraction, per tooth',
  },
  {
    id: 'proc_031',
    code: 'SURG-SURGICAL-COMP',
    name: 'Surgical extraction complicated',
    categoryCode: 'SURG',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Complicated surgical extraction, per tooth',
  },
  {
    id: 'proc_032',
    code: 'SURG-FRENECTOMY',
    name: 'Frenectomy',
    categoryCode: 'SURG',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Frenectomy procedure',
  },
  {
    id: 'proc_033',
    code: 'SURG-EXCISION',
    name: 'Surgical excision of fibroma, pyogenic granuloma etc',
    categoryCode: 'SURG',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Excision of oral soft tissue lesions',
  },
  {
    id: 'proc_034',
    code: 'SURG-DRAINAGE',
    name: 'Surgical drainage',
    categoryCode: 'SURG',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Incision and drainage of abscess',
  },
  {
    id: 'proc_035',
    code: 'SURG-EYELET',
    name: 'Eyelet wiring',
    categoryCode: 'SURG',
    basePrice: 100000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Eyelet wiring for IMF',
  },
  {
    id: 'proc_036',
    code: 'SURG-IMF',
    name: 'IMF (intermaxillary fixation)',
    categoryCode: 'SURG',
    basePrice: 1000000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Intermaxillary fixation procedure',
  },

  // ── PROSTHODONTICS ───────────────────────────────────────────────────
  {
    id: 'proc_037',
    code: 'PROS-CD-UPPER-LOWER',
    name: 'Complete denture upper and lower',
    categoryCode: 'PROS',
    basePrice: 3000000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Full upper and lower complete dentures',
  },
  {
    id: 'proc_038',
    code: 'PROS-CD-ONE-ARCH',
    name: 'Complete denture one arch',
    categoryCode: 'PROS',
    basePrice: 1500000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Complete denture for one arch (upper or lower)',
  },
  {
    id: 'proc_039',
    code: 'PROS-PARTIAL-PER-TOOTH',
    name: 'Partial denture (per additional tooth)',
    categoryCode: 'PROS',
    basePrice: 100000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Partial denture – 100,000 per tooth (single tooth 200,000)',
  },
  {
    id: 'proc_040',
    code: 'PROS-FLEXIBLE-PER-TOOTH',
    name: 'Flexible partial denture (per additional tooth)',
    categoryCode: 'PROS',
    basePrice: 160000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Flexible partial denture – 160,000 per tooth (single tooth 300,000)',
  },
  {
    id: 'proc_041',
    code: 'PROS-REPAIR',
    name: 'Denture repair / addition of teeth or clasp',
    categoryCode: 'PROS',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Repair of removable denture',
  },
  {
    id: 'proc_042',
    code: 'PROS-REBASE-RELINE',
    name: 'Denture rebasing and relining',
    categoryCode: 'PROS',
    basePrice: 120000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Laboratory reline / rebase of denture',
  },
  {
    id: 'proc_043',
    code: 'PROS-NIGHT-GUARD',
    name: 'Night guard',
    categoryCode: 'PROS',
    basePrice: 210000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Custom occlusal night guard',
  },

  // ── FIXED PROSTHESIS ─────────────────────────────────────────────────
  {
    id: 'proc_044',
    code: 'FIXED-ACRYLIC',
    name: 'Acrylic',
    categoryCode: 'FIXED-PROS',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Acrylic provisional crown, per tooth',
  },
  {
    id: 'proc_045',
    code: 'FIXED-PFM',
    name: 'PFM / ceramic',
    categoryCode: 'FIXED-PROS',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Porcelain fused to metal crown, per tooth',
  },
  {
    id: 'proc_046',
    code: 'FIXED-ZIRCONIA',
    name: 'Full Zirconia',
    categoryCode: 'FIXED-PROS',
    basePrice: 600000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Full zirconia crown, per tooth',
  },
  {
    id: 'proc_047',
    code: 'FIXED-VENEER-ZIR',
    name: 'Veneer zirconia',
    categoryCode: 'FIXED-PROS',
    basePrice: 600000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Zirconia veneer, per tooth',
  },
  {
    id: 'proc_048',
    code: 'FIXED-INLAY-ONLAY',
    name: 'Inlay/onlay',
    categoryCode: 'FIXED-PROS',
    basePrice: 600000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Ceramic inlay/onlay restoration, per tooth',
  },

  // ── PERIODONTICS ─────────────────────────────────────────────────────
  {
    id: 'proc_049',
    code: 'PERIO-SCALING-MILD',
    name: 'Full mouth scaling and polishing mild',
    categoryCode: 'PERIO',
    basePrice: 80000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Prophylaxis – mild case',
  },
  {
    id: 'proc_050',
    code: 'PERIO-SCALING-MOD',
    name: 'Full mouth scaling and polishing moderate',
    categoryCode: 'PERIO',
    basePrice: 100000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Prophylaxis – moderate case',
  },
  {
    id: 'proc_051',
    code: 'PERIO-SCALING-SEV',
    name: 'Full mouth scaling and polishing severe',
    categoryCode: 'PERIO',
    basePrice: 120000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Prophylaxis – severe case',
  },
  {
    id: 'proc_052',
    code: 'PERIO-GINGIVECTOMY-TOOTH',
    name: 'Gingivectomy single tooth',
    categoryCode: 'PERIO',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Gingivectomy – per tooth',
  },
  {
    id: 'proc_053',
    code: 'PERIO-GINGIVECTOMY-ARCH',
    name: 'Gingivectomy full arch',
    categoryCode: 'PERIO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Gingivectomy – per arch',
  },

  // ── ORTHODONTICS ─────────────────────────────────────────────────────
  {
    id: 'proc_054',
    code: 'ORTHO-FIXED-ONE-ARCH',
    name: 'Fixed ortho one arch',
    categoryCode: 'ORTHO',
    basePrice: 900000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Fixed orthodontic appliance – one arch',
  },
  {
    id: 'proc_055',
    code: 'ORTHO-FIXED-BOTH-ARCHES',
    name: 'Fixed ortho both arches',
    categoryCode: 'ORTHO',
    basePrice: 1800000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Fixed orthodontic appliance – both arches',
  },
  {
    id: 'proc_056',
    code: 'ORTHO-JACK-SCREW',
    name: 'Removable appliance jack screw',
    categoryCode: 'ORTHO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Removable appliance with expansion screw',
  },
  {
    id: 'proc_057',
    code: 'ORTHO-HYRAX',
    name: 'Fixed appliance hyrax',
    categoryCode: 'ORTHO',
    basePrice: 500000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Hyrax rapid palatal expander',
  },
  {
    id: 'proc_058',
    code: 'ORTHO-HAWLEY-RETAINER',
    name: 'Removable retainer hawley (per arch)',
    categoryCode: 'ORTHO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Hawley retainer – per arch',
  },
  {
    id: 'proc_059',
    code: 'ORTHO-ESSIX-RETAINER',
    name: 'Removable retainer clear (essix)',
    categoryCode: 'ORTHO',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Clear essix retainer – per arch',
  },
  {
    id: 'proc_060',
    code: 'ORTHO-FIXED-RETAINER',
    name: 'Fixed retainer',
    categoryCode: 'ORTHO',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Bonded fixed retainer – per arch',
  },
  {
    id: 'proc_061',
    code: 'ORTHO-HABIT-BREAK',
    name: 'Habit breaking appliance',
    categoryCode: 'ORTHO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Appliance for thumb sucking / tongue thrust',
  },
  {
    id: 'proc_062',
    code: 'ORTHO-FOLLOW-UP',
    name: 'Ortho follow up',
    categoryCode: 'ORTHO',
    basePrice: 40000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Routine orthodontic adjustment – per arch',
  },
  {
    id: 'proc_063',
    code: 'ORTHO-REBOND-BRACKET',
    name: 'Re-bonding of bracket/buccal tube',
    categoryCode: 'ORTHO',
    basePrice: 20000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_BRACKET,
    billingUnit: BillingUnit.BRACKET,
    description: 'Re‑bond one bracket or buccal tube',
  },
  {
    id: 'proc_064',
    code: 'ORTHO-LOST-BRACKET',
    name: 'Lost bracket/buccal tube',
    categoryCode: 'ORTHO',
    basePrice: 35000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_BRACKET,
    billingUnit: BillingUnit.BRACKET,
    description: 'Replacement of lost bracket or buccal tube',
  },
  {
    id: 'proc_065',
    code: 'ORTHO-FUNCTIONAL',
    name: 'Functional appliance',
    categoryCode: 'ORTHO',
    basePrice: 300000,
    currency: 'UGX',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Functional orthodontic appliance',
  },
  {
    id: 'proc_066',
    code: 'ORTHO-CANINE-EXPOSURE',
    name: 'Canine exposure',
    categoryCode: 'ORTHO',
    basePrice: 150000,
    currency: 'UGX',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Surgical exposure of impacted canine, per tooth',
  },

  // ── IMPLANTOLOGY (prices in USD) ──────────────────────────────────────
  {
    id: 'proc_067',
    code: 'IMPLANT-SINGLE',
    name: 'Single implant',
    categoryCode: 'IMPLANT',
    basePrice: 800,
    currency: 'USD',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Single dental implant (fixture only)',
  },
  {
    id: 'proc_068',
    code: 'IMPLANT-BONE-GRAFT',
    name: 'Single implant with bone graft',
    categoryCode: 'IMPLANT',
    basePrice: 1000,
    currency: 'USD',
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    description: 'Implant placement with simultaneous bone graft',
  },
  {
    id: 'proc_069',
    code: 'IMPLANT-OVERDENTURE-ONE-ARCH',
    name: 'Implant supported complete denture – one arch',
    categoryCode: 'IMPLANT',
    basePrice: 5000,
    currency: 'USD',
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    description: 'Implant‑retained overdenture, one arch',
  },
  {
    id: 'proc_070',
    code: 'IMPLANT-OVERDENTURE-BOTH',
    name: 'Implant supported complete denture – both arches',
    categoryCode: 'IMPLANT',
    basePrice: 10000,
    currency: 'USD',
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    description: 'Implant‑retained overdenture, both arches',
  },
];

export async function seedProcedures() {
  console.log('🌱 Seeding Procedures...');

  // Fetch all procedure categories and build a code → id map
  const categories = await prisma.procedureCategory.findMany({
    where: { isActive: true },
    select: { id: true, code: true },
  });
  const categoryMap = new Map<string, string>();
  for (const cat of categories) {
    if (cat.code) categoryMap.set(cat.code, cat.id);
  }

  let seeded = 0;
  for (const proc of procedures) {
    const categoryId = categoryMap.get(proc.categoryCode);
    if (!categoryId) {
      console.warn(`  ⚠ Category code "${proc.categoryCode}" not found – skipping "${proc.name}"`);
      continue;
    }

    const { categoryCode, ...data } = proc;
    await prisma.procedure.upsert({
      where: { id: proc.id },
      update: {
        name: data.name,
        basePrice: data.basePrice,
        currency: data.currency,
        pricingModel: data.pricingModel,
        billingUnit: data.billingUnit ?? null,
        description: data.description,
        categoryId,
      },
      create: {
        id: data.id,
        code: data.code,
        name: data.name,
        basePrice: data.basePrice,
        currency: data.currency,
        pricingModel: data.pricingModel,
        billingUnit: data.billingUnit ?? null,
        description: data.description,
        categoryId,
      },
    });
    seeded++;
  }

  console.log(`✅ Seeded ${seeded} procedures\n`);
}

// Standalone execution (optional)
if (require.main === module) {
  seedProcedures()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}