// prisma/seed/procedures.seed.ts
import { PrismaClient, PricingModel, BillingUnit } from '@prisma/client';

const prisma = new PrismaClient();

const procedures = [
  // ==================== CONSULTATION ====================
  {
    id: 'proc_CONS_001',
    code: 'CONS-GENERAL',
    name: 'General Consultation',
    categoryId: 'cat_012',
    description: 'General dental consultation and assessment',
    baseCost: 5000,
    basePrice: 15000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 15000,
    priceRangeMax: 15000,
    currency: 'UGX',
    defaultDuration: 20,
    requiresXray: false,
    isActive: true,
  },

  // ==================== CONSERVATIVE & ENDODONTICS - Fillings ====================
  {
    id: 'proc_COMP_001',
    code: 'COMP-C5-C1-SHALLOW',
    name: 'Composite Filling - Class 5 & 1 Shallow',
    categoryId: 'cat_015',
    description: 'Tooth-colored composite restoration for shallow cavities (Class 5, 1)',
    baseCost: 20000,
    basePrice: 50000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 50000,
    priceRangeMax: 50000,
    currency: 'UGX',
    defaultDuration: 40,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_COMP_002',
    code: 'COMP-C3-C4-C1-DEEP',
    name: 'Composite Filling - Class 3, 4, 1 Deep',
    categoryId: 'cat_015',
    description: 'Tooth-colored composite restoration for deep cavities (Class 3, 4, 1)',
    baseCost: 35000,
    basePrice: 80000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 80000,
    priceRangeMax: 80000,
    currency: 'UGX',
    defaultDuration: 50,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_COMP_003',
    code: 'COMP-C2',
    name: 'Composite Filling - Class 2',
    categoryId: 'cat_015',
    description: 'Tooth-colored composite restoration for Class 2 cavities (proximal surfaces)',
    baseCost: 45000,
    basePrice: 100000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 100000,
    priceRangeMax: 100000,
    currency: 'UGX',
    defaultDuration: 55,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_GIC_001',
    code: 'GIC-FILL',
    name: 'GIC Filling',
    categoryId: 'cat_015',
    description: 'Glass Ionomer Cement restoration',
    baseCost: 20000,
    basePrice: 50000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 50000,
    priceRangeMax: 50000,
    currency: 'UGX',
    defaultDuration: 35,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_AMAL_001',
    code: 'AMALGAM',
    name: 'Amalgam Restoration',
    categoryId: 'cat_015',
    description: 'Silver amalgam filling for posterior teeth',
    baseCost: 20000,
    basePrice: 50000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 50000,
    priceRangeMax: 50000,
    currency: 'UGX',
    defaultDuration: 40,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_PULP_001',
    code: 'PULP-CAP-INDIRECT',
    name: 'Indirect Pulp Capping',
    categoryId: 'cat_015',
    description: 'Protective liner placement to preserve pulp vitality',
    baseCost: 40000,
    basePrice: 100000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 100000,
    priceRangeMax: 100000,
    currency: 'UGX',
    defaultDuration: 45,
    requiresXray: false,
    isActive: true,
  },

  // ==================== ROOT CANAL THERAPY ====================
  {
    id: 'proc_RCT_001',
    code: 'RCT-1CANAL',
    name: 'Root Canal Therapy - 1 Canal',
    categoryId: 'cat_017',
    description: 'Endodontic treatment for single-canal tooth',
    baseCost: 80000,
    basePrice: 200000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 200000,
    priceRangeMax: 200000,
    currency: 'UGX',
    defaultDuration: 75,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_RCT_002',
    code: 'RCT-2CANAL',
    name: 'Root Canal Therapy - 2 Canals',
    categoryId: 'cat_017',
    description: 'Endodontic treatment for two-canal tooth',
    baseCost: 100000,
    basePrice: 250000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 250000,
    priceRangeMax: 250000,
    currency: 'UGX',
    defaultDuration: 90,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_RCT_003',
    code: 'RCT-3-4CANAL',
    name: 'Root Canal Therapy - 3 to 4 Canals',
    categoryId: 'cat_017',
    description: 'Endodontic treatment for multi-canal tooth (molars)',
    baseCost: 130000,
    basePrice: 300000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 110,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_RCT_004',
    code: 'RCT-RETREAT',
    name: 'Retreatment RCT',
    categoryId: 'cat_018',
    description: 'Re-treatment of previously treated root canal',
    baseCost: 130000,
    basePrice: 300000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 120,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_POST_001',
    code: 'POST-CORE',
    name: 'Post and Core Build Up',
    categoryId: 'cat_017',
    description: 'Core buildup with post placement after RCT',
    baseCost: 150000,
    basePrice: 350000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 350000,
    priceRangeMax: 350000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: true,
    isActive: true,
  },

  // ==================== COSMETIC ====================
  {
    id: 'proc_BLEACH_001',
    code: 'BLEACHING',
    name: 'Teeth Bleaching',
    categoryId: 'cat_035',
    description: 'Professional teeth whitening treatment',
    baseCost: 300000,
    basePrice: 800000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 800000,
    priceRangeMax: 800000,
    currency: 'UGX',
    defaultDuration: 90,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_VENEER_COMP_001',
    code: 'VENEER-COMPOSITE',
    name: 'Composite Veneers',
    categoryId: 'cat_036',
    description: 'Direct composite veneer for aesthetic enhancement',
    baseCost: 20000,
    basePrice: 50000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 50000,
    priceRangeMax: 50000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: false,
    isActive: true,
  },

  // ==================== DIAGNOSTICS ====================
  {
    id: 'proc_XRAY_001',
    code: 'XRAY-STANDARD',
    name: 'X-Ray (Standard)',
    categoryId: 'cat_033',
    description: 'Standard dental radiograph',
    baseCost: 10000,
    basePrice: 25000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 25000,
    priceRangeMax: 25000,
    currency: 'UGX',
    defaultDuration: 5,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_XRAY_002',
    code: 'XRAY-RCT',
    name: 'X-Ray within RCT',
    categoryId: 'cat_033',
    description: 'Radiograph taken during root canal treatment',
    baseCost: 6000,
    basePrice: 15000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 15000,
    priceRangeMax: 15000,
    currency: 'UGX',
    defaultDuration: 3,
    requiresXray: false,
    isActive: true,
  },

  // ==================== PEDODONTICS ====================
  {
    id: 'proc_PEDO_EXT_001',
    code: 'PEDO-EXTRACTION',
    name: 'Pediatric Extraction',
    categoryId: 'cat_031',
    description: 'Tooth extraction for pediatric patients',
    baseCost: 12000,
    basePrice: 30000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 30000,
    priceRangeMax: 30000,
    currency: 'UGX',
    defaultDuration: 20,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_PEDO_GIC_001',
    code: 'PEDO-GIC-FILL',
    name: 'Pediatric GIC Filling',
    categoryId: 'cat_031',
    description: 'Glass Ionomer filling for children',
    baseCost: 14000,
    basePrice: 35000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 35000,
    priceRangeMax: 35000,
    currency: 'UGX',
    defaultDuration: 30,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_PEDO_PULPO_001',
    code: 'PULPOTOMY',
    name: 'Pulpotomy',
    categoryId: 'cat_017',
    description: 'Partial pulp removal for primary teeth',
    baseCost: 16000,
    basePrice: 40000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 40000,
    priceRangeMax: 40000,
    currency: 'UGX',
    defaultDuration: 40,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_PEDO_PULPEC_001',
    code: 'PULPECTOMY',
    name: 'Pulpectomy',
    categoryId: 'cat_017',
    description: 'Complete pulp removal for primary teeth',
    baseCost: 40000,
    basePrice: 100000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 100000,
    priceRangeMax: 100000,
    currency: 'UGX',
    defaultDuration: 55,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_PEDO_SSC_001',
    code: 'SSC-CROWN',
    name: 'Stainless Steel Crown',
    categoryId: 'cat_022',
    description: 'Prefabricated stainless steel crown for primary teeth',
    baseCost: 80000,
    basePrice: 200000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 200000,
    priceRangeMax: 200000,
    currency: 'UGX',
    defaultDuration: 45,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_PEDO_SPACE_001',
    code: 'SPACE-MAINTAINER-BL',
    name: 'Space Maintainer - Band and Loop',
    categoryId: 'cat_032',
    description: 'Fixed space maintainer to preserve arch length',
    baseCost: 120000,
    basePrice: 300000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 50,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_PEDO_SCALE_001',
    code: 'PEDO-SCALING',
    name: 'Pediatric Scaling',
    categoryId: 'cat_013',
    description: 'Professional cleaning for children',
    baseCost: 16000,
    basePrice: 40000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 40000,
    priceRangeMax: 40000,
    currency: 'UGX',
    defaultDuration: 30,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_PEDO_FLUOR_001',
    code: 'FLUORIDE-APP',
    name: 'Fluoride Application',
    categoryId: 'cat_014',
    description: 'Topical fluoride treatment for cavity prevention',
    baseCost: 20000,
    basePrice: 50000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 50000,
    priceRangeMax: 50000,
    currency: 'UGX',
    defaultDuration: 10,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_PEDO_SEAL_001',
    code: 'SEALANT-PIT-FISSURE',
    name: 'Pit and Fissure Sealant',
    categoryId: 'cat_014',
    description: 'Preventive sealant application on molars',
    baseCost: 20000,
    basePrice: 50000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 50000,
    priceRangeMax: 50000,
    currency: 'UGX',
    defaultDuration: 15,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_PEDO_SURG_001',
    code: 'SURG-EXPOSURE-UNERUPTED',
    name: 'Surgical Exposure of Unerupted Teeth',
    categoryId: 'cat_020',
    description: 'Surgical procedure to expose impacted or unerupted teeth',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 50,
    requiresXray: true,
    isActive: true,
  },

  // ==================== SURGERY - Extractions ====================
  {
    id: 'proc_EXT_ANT_001',
    code: 'EXT-ANTERIOR',
    name: 'Extraction - Anterior Tooth',
    categoryId: 'cat_019',
    description: 'Simple extraction of front tooth',
    baseCost: 20000,
    basePrice: 50000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 50000,
    priceRangeMax: 50000,
    currency: 'UGX',
    defaultDuration: 20,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_EXT_PREM_001',
    code: 'EXT-PREMOLAR',
    name: 'Extraction - Premolar',
    categoryId: 'cat_019',
    description: 'Simple extraction of premolar tooth',
    baseCost: 24000,
    basePrice: 60000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 60000,
    priceRangeMax: 60000,
    currency: 'UGX',
    defaultDuration: 25,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_EXT_MOL_001',
    code: 'EXT-MOLAR',
    name: 'Extraction - Molar',
    categoryId: 'cat_019',
    description: 'Simple extraction of molar tooth',
    baseCost: 28000,
    basePrice: 70000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 70000,
    priceRangeMax: 70000,
    currency: 'UGX',
    defaultDuration: 30,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_EXT_WIS_001',
    code: 'EXT-WISDOM',
    name: 'Extraction - Wisdom Teeth',
    categoryId: 'cat_019',
    description: 'Extraction of third molar (wisdom tooth)',
    baseCost: 32000,
    basePrice: 80000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 80000,
    priceRangeMax: 80000,
    currency: 'UGX',
    defaultDuration: 35,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_EXT_SURG_S_001',
    code: 'SURG-EXT-SIMPLE',
    name: 'Surgical Extraction - Simple',
    categoryId: 'cat_020',
    description: 'Surgical removal of tooth with minimal bone removal',
    baseCost: 40000,
    basePrice: 100000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 100000,
    priceRangeMax: 100000,
    currency: 'UGX',
    defaultDuration: 45,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_EXT_SURG_C_001',
    code: 'SURG-EXT-COMPLICATED',
    name: 'Surgical Extraction - Complicated',
    categoryId: 'cat_020',
    description: 'Complex surgical extraction with significant bone removal',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: true,
    isActive: true,
  },

  // ==================== SURGERY - Oral Surgery ====================
  {
    id: 'proc_FREN_001',
    code: 'FRENECTOMY',
    name: 'Frenectomy',
    categoryId: 'cat_021',
    description: 'Surgical removal or modification of oral frenum',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 30,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_LESION_001',
    code: 'LESION-EXCISION',
    name: 'Surgical Excision - Fibroma/Pyogenic Granuloma',
    categoryId: 'cat_021',
    description: 'Removal of benign oral soft tissue lesions',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 40,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_DRAIN_001',
    code: 'SURG-DRAINAGE',
    name: 'Surgical Drainage',
    categoryId: 'cat_021',
    description: 'Incision and drainage of dental abscess',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 35,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_EYELET_001',
    code: 'EYELET-WIRING',
    name: 'Eyelet Wiring',
    categoryId: 'cat_004',
    description: 'Orthodontic/surgical wiring for jaw stabilization',
    baseCost: 40000,
    basePrice: 100000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 100000,
    priceRangeMax: 100000,
    currency: 'UGX',
    defaultDuration: 45,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_IMF_001',
    code: 'IMF-FIXATION',
    name: 'IMF - Intermaxillary Fixation',
    categoryId: 'cat_004',
    description: 'Jaw wiring for fracture stabilization',
    baseCost: 400000,
    basePrice: 1000000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 1000000,
    priceRangeMax: 1000000,
    currency: 'UGX',
    defaultDuration: 120,
    requiresXray: true,
    isActive: true,
  },

  // ==================== PROSTHODONTICS - Dentures ====================
  {
    id: 'proc_DENT_COMP_001',
    code: 'DENT-COMPLETE-BOTH',
    name: 'Complete Denture - Upper and Lower',
    categoryId: 'cat_024',
    description: 'Full acrylic denture for both arches',
    baseCost: 1200000,
    basePrice: 3000000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 3000000,
    priceRangeMax: 3000000,
    currency: 'UGX',
    defaultDuration: 300,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_DENT_COMP_002',
    code: 'DENT-COMPLETE-ONE',
    name: 'Complete Denture - One Arch',
    categoryId: 'cat_024',
    description: 'Full acrylic denture for single arch',
    baseCost: 600000,
    basePrice: 1500000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 1500000,
    priceRangeMax: 1500000,
    currency: 'UGX',
    defaultDuration: 200,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_DENT_PART_001',
    code: 'DENT-PARTIAL-PER-TOOTH',
    name: 'Partial Denture - Per Tooth',
    categoryId: 'cat_024',
    description: 'Removable partial denture (price per tooth)',
    baseCost: 40000,
    basePrice: 100000,
    pricingModel: PricingModel.PER_UNIT,
    billingUnit: BillingUnit.UNIT,
    priceRangeMin: 200000,
    priceRangeMax: 1000000,
    currency: 'UGX',
    defaultDuration: 120,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_DENT_FLEX_001',
    code: 'DENT-FLEXIBLE-PER-TOOTH',
    name: 'Flexible Partial Denture - Per Tooth',
    categoryId: 'cat_024',
    description: 'Flexible valplast partial denture (price per tooth)',
    baseCost: 64000,
    basePrice: 160000,
    pricingModel: PricingModel.PER_UNIT,
    billingUnit: BillingUnit.UNIT,
    priceRangeMin: 300000,
    priceRangeMax: 1600000,
    currency: 'UGX',
    defaultDuration: 150,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_DENT_REPAIR_001',
    code: 'DENT-REPAIR-ADD',
    name: 'Denture Repair / Addition of Teeth or Clasp',
    categoryId: 'cat_024',
    description: 'Repair or modification of existing denture',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_DENT_REBASE_001',
    code: 'DENT-REBASE-RELINE',
    name: 'Denture Rebasing and Relining',
    categoryId: 'cat_024',
    description: 'Refitting of denture base for improved fit',
    baseCost: 48000,
    basePrice: 120000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 120000,
    priceRangeMax: 120000,
    currency: 'UGX',
    defaultDuration: 90,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_NIGHT_001',
    code: 'NIGHT-GUARD',
    name: 'Night Guard',
    categoryId: 'cat_024',
    description: 'Occlusal splint for bruxism protection',
    baseCost: 84000,
    basePrice: 210000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 210000,
    priceRangeMax: 210000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: false,
    isActive: true,
  },

  // ==================== PROSTHODONTICS - Crowns & Fixed ====================
  {
    id: 'proc_CROWN_ACR_001',
    code: 'CROWN-ACRYLIC',
    name: 'Fixed Prosthesis - Acrylic Crown',
    categoryId: 'cat_022',
    description: 'Acrylic crown for temporary or budget restoration',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_CROWN_PFM_001',
    code: 'CROWN-PFM-CERAMIC',
    name: 'Crown - PFM / Ceramic',
    categoryId: 'cat_022',
    description: 'Porcelain-fused-to-metal or full ceramic crown',
    baseCost: 120000,
    basePrice: 300000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 90,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_CROWN_ZIR_001',
    code: 'CROWN-FULL-ZIRCONIA',
    name: 'Crown - Full Zirconia',
    categoryId: 'cat_022',
    description: 'Monolithic zirconia crown for strength and aesthetics',
    baseCost: 240000,
    basePrice: 600000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 600000,
    priceRangeMax: 600000,
    currency: 'UGX',
    defaultDuration: 100,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_VENEER_ZIR_001',
    code: 'VENEER-ZIRCONIA',
    name: 'Veneer - Zirconia',
    categoryId: 'cat_036',
    description: 'Zirconia veneer for premium aesthetic restoration',
    baseCost: 240000,
    basePrice: 600000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 600000,
    priceRangeMax: 600000,
    currency: 'UGX',
    defaultDuration: 90,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_INLAY_001',
    code: 'INLAY-ONLAY',
    name: 'Inlay / Onlay',
    categoryId: 'cat_016',
    description: 'Indirect restoration for moderate to large cavities',
    baseCost: 240000,
    basePrice: 600000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 600000,
    priceRangeMax: 600000,
    currency: 'UGX',
    defaultDuration: 100,
    requiresXray: true,
    isActive: true,
  },

  // ==================== PERIODONTICS ====================
  {
    id: 'proc_SCALE_MILD_001',
    code: 'SCALE-POLISH-MILD',
    name: 'Full Mouth Scaling & Polishing - Mild',
    categoryId: 'cat_029',
    description: 'Professional cleaning for mild calculus buildup',
    baseCost: 32000,
    basePrice: 80000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 80000,
    priceRangeMax: 80000,
    currency: 'UGX',
    defaultDuration: 45,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_SCALE_MOD_001',
    code: 'SCALE-POLISH-MODERATE',
    name: 'Full Mouth Scaling & Polishing - Moderate',
    categoryId: 'cat_029',
    description: 'Professional cleaning for moderate calculus buildup',
    baseCost: 40000,
    basePrice: 100000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 100000,
    priceRangeMax: 100000,
    currency: 'UGX',
    defaultDuration: 55,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_SCALE_SEV_001',
    code: 'SCALE-POLISH-SEVERE',
    name: 'Full Mouth Scaling & Polishing - Severe',
    categoryId: 'cat_029',
    description: 'Professional cleaning for severe calculus buildup',
    baseCost: 48000,
    basePrice: 120000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 120000,
    priceRangeMax: 120000,
    currency: 'UGX',
    defaultDuration: 70,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_GING_SINGLE_001',
    code: 'GINGIVECTOMY-SINGLE',
    name: 'Gingivectomy - Single Tooth',
    categoryId: 'cat_030',
    description: 'Gum contouring for single tooth',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 40,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_GING_ARCH_001',
    code: 'GINGIVECTOMY-ARCH',
    name: 'Gingivectomy - Full Arch',
    categoryId: 'cat_030',
    description: 'Gum contouring for entire arch',
    baseCost: 120000,
    basePrice: 300000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 75,
    requiresXray: false,
    isActive: true,
  },

  // ==================== ORTHODONTICS ====================
  {
    id: 'proc_ORTHO_FIX_1_001',
    code: 'ORTHO-FIXED-ONE-ARCH',
    name: 'Fixed Orthodontics - One Arch',
    categoryId: 'cat_026',
    description: 'Traditional braces treatment for single arch',
    baseCost: 360000,
    basePrice: 900000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 900000,
    priceRangeMax: 900000,
    currency: 'UGX',
    defaultDuration: 120,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_FIX_2_001',
    code: 'ORTHO-FIXED-BOTH-ARCHES',
    name: 'Fixed Orthodontics - Both Arches',
    categoryId: 'cat_026',
    description: 'Traditional braces treatment for both arches',
    baseCost: 720000,
    basePrice: 1800000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 1800000,
    priceRangeMax: 1800000,
    currency: 'UGX',
    defaultDuration: 120,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_REM_JACK_001',
    code: 'ORTHO-REMOVABLE-JACKSCREW',
    name: 'Removable Appliance - Jack Screw',
    categoryId: 'cat_027',
    description: 'Removable orthodontic appliance with expansion screw',
    baseCost: 120000,
    basePrice: 300000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_HYRAX_001',
    code: 'ORTHO-FIXED-HYRAX',
    name: 'Fixed Appliance - Hyrax Expander',
    categoryId: 'cat_026',
    description: 'Fixed palatal expander for arch widening',
    baseCost: 200000,
    basePrice: 500000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 500000,
    priceRangeMax: 500000,
    currency: 'UGX',
    defaultDuration: 75,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_RET_HAWLEY_001',
    code: 'RETAINER-HAWLEY',
    name: 'Removable Retainer - Hawley',
    categoryId: 'cat_028',
    description: 'Traditional acrylic and wire retainer',
    baseCost: 120000,
    basePrice: 300000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 45,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_RET_ESSIX_001',
    code: 'RETAINER-ESSIX',
    name: 'Removable Retainer - Clear (Essix)',
    categoryId: 'cat_028',
    description: 'Clear vacuum-formed retainer',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 30,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_RET_FIXED_001',
    code: 'RETAINER-FIXED',
    name: 'Fixed Retainer',
    categoryId: 'cat_028',
    description: 'Bonded wire retainer for long-term retention',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 40,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_HABIT_001',
    code: 'HABIT-BREAKING-APPLIANCE',
    name: 'Habit Breaking Appliance',
    categoryId: 'cat_026',
    description: 'Appliance to correct thumb sucking or tongue thrusting',
    baseCost: 120000,
    basePrice: 300000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 60,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_FOLLOW_001',
    code: 'ORTHO-FOLLOWUP',
    name: 'Orthodontic Follow Up',
    categoryId: 'cat_026',
    description: 'Routine adjustment visit during orthodontic treatment',
    baseCost: 16000,
    basePrice: 40000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 40000,
    priceRangeMax: 40000,
    currency: 'UGX',
    defaultDuration: 20,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_REBOND_001',
    code: 'ORTHO-REBOND-BRACKET',
    name: 'Re-bonding of Bracket / Buccal Tube',
    categoryId: 'cat_026',
    description: 'Re-attachment of loose orthodontic bracket or tube',
    baseCost: 8000,
    basePrice: 20000,
    pricingModel: PricingModel.PER_UNIT,
    billingUnit: BillingUnit.UNIT,
    priceRangeMin: 20000,
    priceRangeMax: 20000,
    currency: 'UGX',
    defaultDuration: 15,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_LOST_001',
    code: 'ORTHO-LOST-BRACKET',
    name: 'Lost Bracket / Buccal Tube Replacement',
    categoryId: 'cat_026',
    description: 'Replacement of lost or broken orthodontic bracket or tube',
    baseCost: 14000,
    basePrice: 35000,
    pricingModel: PricingModel.PER_UNIT,
    billingUnit: BillingUnit.UNIT,
    priceRangeMin: 35000,
    priceRangeMax: 35000,
    currency: 'UGX',
    defaultDuration: 20,
    requiresXray: false,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_FUNC_001',
    code: 'FUNCTIONAL-APPLIANCE',
    name: 'Functional Appliance',
    categoryId: 'cat_026',
    description: 'Removable appliance for jaw growth modification',
    baseCost: 120000,
    basePrice: 300000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 300000,
    priceRangeMax: 300000,
    currency: 'UGX',
    defaultDuration: 75,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_ORTHO_CANINE_001',
    code: 'CANINE-EXPOSURE',
    name: 'Canine Exposure',
    categoryId: 'cat_020',
    description: 'Surgical exposure of impacted canine for orthodontic traction',
    baseCost: 60000,
    basePrice: 150000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 150000,
    priceRangeMax: 150000,
    currency: 'UGX',
    defaultDuration: 50,
    requiresXray: true,
    isActive: true,
  },

  // ==================== IMPLANTOLOGY (USD PRICING) ====================
  {
    id: 'proc_IMPL_SINGLE_001',
    code: 'IMPLANT-SINGLE',
    name: 'Single Implant',
    categoryId: 'cat_025',
    description: 'Placement of single dental implant fixture',
    baseCost: 320000,
    basePrice: 800,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 800,
    priceRangeMax: 800,
    currency: 'USD',
    defaultDuration: 90,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_IMPL_GRAFT_001',
    code: 'IMPLANT-SINGLE-BONE-GRAFT',
    name: 'Single Implant with Bone Graft',
    categoryId: 'cat_025',
    description: 'Implant placement with simultaneous bone grafting',
    baseCost: 400000,
    basePrice: 1000,
    pricingModel: PricingModel.PER_TOOTH,
    billingUnit: BillingUnit.TOOTH,
    priceRangeMin: 1000,
    priceRangeMax: 1000,
    currency: 'USD',
    defaultDuration: 120,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_IMPL_DENT_1_001',
    code: 'IMPLANT-DENTURE-ONE-ARCH',
    name: 'Implant-Supported Complete Denture - One Arch',
    categoryId: 'cat_025',
    description: 'Full arch denture supported by dental implants',
    baseCost: 2000000,
    basePrice: 5000,
    pricingModel: PricingModel.PER_ARCH,
    billingUnit: BillingUnit.ARCH,
    priceRangeMin: 5000,
    priceRangeMax: 5000,
    currency: 'USD',
    defaultDuration: 300,
    requiresXray: true,
    isActive: true,
  },
  {
    id: 'proc_IMPL_DENT_2_001',
    code: 'IMPLANT-DENTURE-BOTH-ARCHES',
    name: 'Implant-Supported Complete Denture - Both Arches',
    categoryId: 'cat_025',
    description: 'Full mouth rehabilitation with implant-supported dentures',
    baseCost: 4000000,
    basePrice: 10000,
    pricingModel: PricingModel.FIXED,
    billingUnit: null,
    priceRangeMin: 10000,
    priceRangeMax: 10000,
    currency: 'USD',
    defaultDuration: 480,
    requiresXray: true,
    isActive: true,
  },
];

export async function seedProcedures() {
  console.log('🦷 Seeding Procedures...');

  // Upsert each procedure using the exact pattern from your categories seed
  for (const proc of procedures) {
    await prisma.procedure.upsert({
      where: { id: proc.id },
      update: {}, // No updates on re-run - keeps existing data intact
      create: proc,
    });
    console.log(`  ✓ Upserted procedure: ${proc.name}`);
  }

  console.log(`✅ Seeded ${procedures.length} procedures\n`);
  return procedures.length;
}

// Standalone execution - matches your category seed pattern exactly
if (require.main === module) {
  seedProcedures()
    .catch((e) => {
      console.error('❌ Seed failed:', e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}